name: REDPAN

#channels:
#  - conda-forge
#  - defaults
  
dependencies:
  - python==3.9
  - anaconda
  - pip

  - pip:
    - ipython
    - sklearn
    - matplotlib==3.3.2  
    - obspy==1.4.1
    - tensorflow==2.14.0
    - tensorflow-addons==0.11.2
    - numpy==1.23.5
    - pandas==1.5.3
    - scipy==1.8.1
    - 
    #- mpi4py=3.0.3
    #- numba
    #- protobuf==3.20.1
