name: REDPAN

#channels:
#  - conda-forge
#  - defaults
  
dependencies:
  - python==3.7.3
  - anaconda
  - pip

  - pip:
    - matplotlib==3.3.2  
    - obspy==1.2.2
    - tensorflow-gpu==2.5.0
    - tensorflow-addons==0.11.2
